### ISSUE TITLE
Syntax error - target='_blank'>

### ISSUE THREAD

**Issue by shanemittun** [mittun/wordpress-twitter-widget#1]
Check out the attached screenshot.
One of the links is showing the text:
`target='_blank'>`

This error is showing up on HRC's live site as of 6-22-2018 at 5:09PM PST

![twitter-widget-issue_new-tab-code-error_uploaded-on-6-22-2018](https://user-images.githubusercontent.com/8688978/41803570-17f71834-763f-11e8-87b1-0bf936b10ecd.png)

**Comment by TylerB24890** [comment]
Issue fixed commit #4369041

**Comment by shanemittun** [comment]
Sweet. Thanks! @TylerB24890
